export default {
  position: 'absolute',
  content: '""',
  right: 'calc(100% - 1px)',
  WebkitBorder: '10px solid transparent',
  MozBorder: '10px solid transparent',
  OBorder: '10px solid transparent',
  border: '10px solid transparent',
  WebkitBorderRightColor: '#FFF',
  MozBorderRightColor: '#FFF',
  OBorderRightColor: '#FFF',
  borderRightColor: '#FFF',
  WebkitFilter: 'drop-shadow(rgba(0, 0, 0, 0.24) -3px 0 2px)',
  filter: 'drop-shadow(rgba(0, 0, 0, 0.24) -3px 0 2px)',
};
